{
    "th07 Menu Start": "Inicia el juego",
    "th07 Menu Extra Start": "Inicia el nivel extra",
    "th07 Menu Practice Start": "Selecciona el nivel e inicia la práctica",
    "th07 Menu Result": "Comprueba el historial de capturas de cartas de conjuro y puntuaciones anteriores",
    "th07 Menu Music Room": "Escucha la música",
    "th07 Menu Replay": "Observa las grabaciones",
    "th07 Menu Option": "Configura todo tipo de opciones",
    "th07 Menu Quit": "Sal por cualquier razón",
    "th07 Bomb Reimu A unfocused": "Signo de espíritu \"Sello de fantasía -Dispersión-\"",
    "th07 Bomb Reimu A focused": "Signo de espíritu \"Sello de fantasía -Concentración-\"",
    "th07 Bomb Reimu B unfocused": "Signo de sueño \"Círculo sellador del mal\"",
    "th07 Bomb Reimu B focused": "Signo de sueño \"Barrera dúplex\"",
    "th07 Bomb Marisa A unfocused": "Signo de magia \"Ensueño de polvo estelar\"",
    "th07 Bomb Marisa A focused": "Signo de magia \"Vía Láctea\"",
    "th07 Bomb Marisa B unfocused": "Signo de amor \"Láser no direccional\"",
    "th07 Bomb Marisa B focused": "Signo de amor \"Chispa maestra\"",
    "th07 Bomb Sakuya A unfocused": "Signo de ilusión \"Indiscriminado\"",
    "th07 Bomb Sakuya A focused": "Signo de ilusión \"Muñeca asesina\"",
    "th07 Bomb Sakuya B unfocused": "Signo de tiempo \"Casilla perfecta\"",
    "th07 Bomb Sakuya B focused": "Signo de tiempo \"Casilla privada\"",
    "th10 Music Room spoiler 1": "<c$**El tema seleccionado no se ha reproducido todavía en el juego**$>",
    "th10 Music Room spoiler 2": "<c$Los comentarios del tema pueden destripar el juego.$>",
    "th10 Music Room spoiler 3": "<c$¿Sigues queriendo reproducir este tema?$>",
    "th10 Music Room spoiler 4": "<c$Vuelve a pulsar el botón Aceptar si quieres reproducir el tema.$>",
    "th10 Music Room spoiler 5": "<c$Aquellos que no quieran reproducir el tema que muevan el cursor.$>",
    "th13 spell nothing": "　Ninguna...",
    "th10 Dialog Prompt": "Seleccione modo de ventana",
    "th10 Dialog Fullscreen": "Completa",
    "th10 Dialog Always ask": "Preguntar siempre al empezar",
    "th11 Dialog Fullscreen 640": "Pantalla completa (640×480)",
    "th11 Dialog Window 640": "Ventana (640×480)",
    "th11 Dialog Window 960": "Ventana (960×720)",
    "th11 Dialog Window 1280": "Ventana (1280×960)",
    "th11 Dialog Game Start": "Iniciar juego",
    "th14 Dialog Prompt": "Seleccione la resolución",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280x960 (recomendada)",
    "th14 Dialog Fullscreen": "Jugar en pantalla completa",
    "th14 Dialog Always ask": "Preguntar siempre al empezar",
    "th10 JP": "Touhou Fuujinroku",
    "alcostg JP": "Tasogare Sakaba",
    "th11 JP": "Touhou Chireiden",
    "th12 JP": "Touhou Seirensen",
    "th125 JP": "Double Spoiler",
    "th128 JP": "Yousei Daisensou",
    "th13 JP": "Touhou Shinreibyou",
    "th14 JP": "Touhou Kishinjou",
    "th06 config": "Configuración de Touhou Koumakyou",
    "th07 config": "Configuración de Touhou Youyoumu",
    "th08 config": "Configuración de Touhou Eiyashou",
    "th09 config": "Configuración de Touhou Kaeidzuka",
    "th095 config": "Configuración de Touhou Bunkachou",
    "th10 config": "Configuración de Touhou Fuujinroku",
    "alcostg config": "Configuración de Tasogare Sakaba",
    "th11 config": "Configuración de Touhou Chireiden",
    "th12 config": "Configuración de Touhou Seirensen",
    "th125 config": "Configuración de Double Spoiler ~ Touhou Bunkachou",
    "th128 config": "Configuración de Yousei Daisensou ~ Touhou Sangetsusei",
    "th13 config": "Configuración de Touhou Shinreibyou",
    "th14 config": "Configuración de Touhou Kishinjou",
    "th06 up": "Arriba ",
    "th06 down": "Abajo ",
    "th06 left": "Izquierda ",
    "th06 right": "Derecha ",
    "th06 vertex": "Deshabilitar Vertex Buffer",
    "th06 fog": "Deshabilitar niebla",
    "th06 16bit textures": "Forzar texturas de 16 bits",
    "th06 Gouraud shading": "Limitar uso del sombreado Gouraud",
    "th06 color composition": "No usar composición de colores en texturas",
    "th06 rasterizer mode": "Utilizar modo de rasterización por referencia",
    "th06 clear buffer": "Limpiar backbuffer durante refresco de pantalla",
    "th06 minimum graphics": "Mostrar gráficos mínimos necesarios",
    "th06 depth test": "Desactivar prueba de profundidad",
    "th06 force frame": "Forzar tasa de imágenes a 60FPS",
    "th06 fullscreen": "Pantalla completa",
    "th06 windowed": "Ventana",
    "th06 full rate": "1/1 (predeter.)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32 bits",
    "th06 16bits mode": "16 bits",
    "th06 accept": "Aceptar",
    "th06 cancel": "Cancelar",
    "th06 screen mode": "Estilo de pantalla",
    "th06 refresh rate": "Frecuencia de actualización",
    "th06 colors": "Modo de color",
    "th06 pad X axis": "Eje X del mando (1~1000)",
    "th06 pad Y axis": "Eje Y del mando (1~1000)",
    "th06 check pad": "Comprobar mando",
    "th06 DirectInput": "No utilizar DirectInput para la entrada",
    "th06 config saved caption": "Confirmación",
    "th06 config saved text": "Configuración guardada",
    "th07 16bits textures": "Forzar uso de texturas de 16 bits",
    "th07 DirectInput": "No utilizar DirectInput para la entrada de mando",
    "th07 BGM memory": "Precargar BGM en la memoria",
    "th07 draw screen": "Dibujar fondo de pantalla en cada momento",
    "th07 VSync": "Desactivar sincronización vertical",
    "th07 fullscreen": "Pantalla completa (rec.)",
    "th07 low effects": "Feo",
    "th07 medium effects": "Modesto",
    "th07 high effects": "Bello (rec.)",
    "th07 32bits mode": "32 bits (recomen.)",
    "th07 effect quality": "Calidad de efectos",
    "th08 fog": "Deshabilitar niebla (no recomendado)",
    "th08 color composition": "No usar composición de colores en texturas (prohibido)",
    "th08 depth test": "Desactivar prueba de profundidad (no recomendado)",
    "th08 rasterizer mode": "Utilizar modo de rasterización por referencia (prohibido)",
    "th08 VSync": "Desactivar sincronización vertical (no recomendado)",
    "th09 full rate": "1/1 (recomen.)",
    "th09 1P controller": "Controlador del 1J",
    "th09 2P controller": "Controlador del 2J",
    "th09 gamepad 1": "Mando 1",
    "th09 gamepad 2": "Mando 2",
    "th09 all keyboard": "Teclado completo",
    "th09 left side keyboard": "Izquierdo",
    "th09 right side keyboard": "Derecho",
    "th09 no save": "Salir sin guardar",
    "th09 save": "Guardar y salir",
    "th10 faith meter": "Mostrar medidor de fe cerca del jugador",
    "th10 screen mode": "Modo de pantalla",
    "th10 always ask": "Preguntar",
    "th10 slowshot": "Focalizar disparo al mantener pulsado el botón de disparo",
    "th11 input latency": "Latencia de entrada",
    "th11 stable input": "Estable (si la entrada no funciona a menudo)",
    "th11 normal input": "Normal (uso de CPU bajo)",
    "th11 automatic input": "Auto (detecta la reacción más rápida) *Predeter.",
    "th11 fast input": "Rápida (si auto no funciona correctamente)",
    "th11 input description": "　Selecciona el tipo de latencia para una precisión de la respuesta de entrada.\n　\"Estable\" y \"Normal\" responden a la entrada del frame anterior.\n　\"Auto\" intentará proporcionar la respuesta más rápida posible.\n　\"Rápida\" es similar a \"Auto\", pero la imagen puede distorsionarse.\n　*No sirve si la frecuencia de actualización no es \"1/1\"*",
    "th11 always ask": "Preguntar siempre al empezar",
    "th11 sensitivity description": "Aumenta la sensibilidad si la entrada direccional es lenta\n(predeterminado: 600)",
    "th11 joypad sensitivity": "Sensibilidad del mando",
    "th11 default": "Restaurar valores predeterminados",
    "th13_ascii_spell_score": "PUNT. %8d0  %4d/%4d",
    "th13_ascii_spell_unknown": "PUNT.        00  ----/----",
    "th13_ascii_spell_game": "MODO DE JUEGO    %4d/%4d",
    "th14_ascii_bonus": "BONUS %.1f",
    "th14_ascii_no_bonus": "SIN BONUS",
    "th10_ascii_stage_1": "Nivel 1",
    "th10_ascii_stage_2": "Nivel 2",
    "th10_ascii_stage_3": "Nivel 3",
    "th10_ascii_stage_4": "Nivel 4",
    "th10_ascii_stage_5": "Nivel 5",
    "th10_ascii_stage_6": "Nivel 6",
    "th10_ascii_stage_clear": "Completado",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  Nivel -  ---%",
    "th10_ascii_ranking": "             Clasificacion!!",
    "th13_ascii_credit": "Creditos %d",
    "th07 Option Player": "Selecciona el número inicial de vidas con las que empizas. (Por defecto: 3)",
    "th06 Bomb Reimu B": "Signo de sueño \"Círculo sellador del mal\"",
    "th06 Bomb Marisa A": "Signo de magia \"Ensueño de polvo estelar\"",
    "th06 Bomb Marisa B": "Signo de amor \"Chispa maestra\"",
    "th07 Option Graphic": "Cambia la profundidad de color de pantalla. Es más bello en 32 bits.",
    "th07 Option BGM": "Cambia la forma de reproducir la música. (Por defecto: WAV)",
    "th07 Option Sound": "Selecciona si se reproducen los efectos de sonido o no.",
    "th07 Option Window Mode": "Cambia entre pantalla completa o modo ventana.",
    "th07 Option Slow Mode": "Ralentiza el juego cuando hay muchos proyectiles en pantalla. (Aunque no tendrás ni grabaciones ni alta puntuación)",
    "th07 Option Reset": "Restaura la configuración por defecto.",
    "th07 Option Key Config": "Configura las teclas de control del mando.",
    "th07 Option Quit": "Abandona el menú de opciones.",
    "th07 Key Shot": "Configura el botón de disparo/confirmar.",
    "th07 Key Bomb": "Configura el botón de bomba/cancelar.",
    "th07 Key Slow": "Configura el botón de movimiento lento.",
    "th07 Key Skip": "Configura el botón de saltar diálogos.",
    "th07 Key Pause": "Configura el botón de pausa.",
    "th07 Key Up": "Configura el botón de movimiento hacia arriba.",
    "th07 Key Down": "Configura el botón de movimiento hacia abajo.",
    "th07 Key Left": "Configura el botón de movimiento a la izquierda.",
    "th07 Key Right": "Configura el botón de movimiento a la derecha.",
    "th07 Key ShotSlow": "Te mueves más lento al mantener pulsado el botón de disparo.",
    "th07 Key Reset": "Restaura la configuración por defecto.",
    "th07 Key Quit": "Abandona la configuración de teclas.",
    "th08 Menu Spell Practice": "Por si quieres practicar las cartas de conjuro de los oponentes.",
    "th08 Option BGM Volume": "Ajusta el volumen de la música.",
    "th06 Bomb Reimu A": "Signo de espíritu \"Sello de fantasía\"",
    "th08 Option SE Volume": "Ajusta el volumen de los efectos de sonido.",
    "th09 Menu Story Start": "Inicia el modo Kaeidzuka.",
    "th09 Menu Extra Start": "Inicia el modo extra.",
    "th09 Menu Match Start": "Inicia el modo JcJ, contra la CPU o espectador.",
    "th09 Menu Replay": "Reproduce las grabaciones.",
    "th09 Menu Result": "Visualiza los registros.",
    "th09 Menu Music Room": "Entra en la sala de música.",
    "th09 Option BGM": "Cambia el método de reproducción de música. *Actualmente MIDI no está soportado.",
    "th09 Option Key Config": "Configura los controles.",
    "th09 Key Side": "Selecciona 1J ó 2J.",
    "th09 Key Control Type": "Mando 1 ó 2: uso del mando; Intro, izquierda o derecha: uso del teclado.",
    "th09 Key Charge Type": "Cambia el comportamiento del botón de carga - Lento: movimiento lento; Carga: cargar disparo.",
    "th09 Key Shot": "Configura el botón de disparo.",
    "th09 Key Bomb": "Configura el botón de bomba.",
    "th09 Key Slow": "Configura el botón de movimiento lento o cargar disparo.",
    "th08 Music Room spoiler 1": "*** Nota ***",
    "th08 Music Room spoiler 2": "　Este tema todavía no se ha reproducido en el juego.",
    "th08 Music Room spoiler 3": "　Si todavía no quieres escuchar el tema o ver el comentario,",
    "th08 Music Room spoiler 4": "　será mejor que te alejes lo antes posible.",
    "th08 Music Room spoiler 5": "　",
    "th08 Music Room spoiler 6": "　　(Atención, si pulsas otra vez el botón aceptar, al igual que en los otros temas,",
    "th08 Music Room spoiler 7": "　　se mostrará el comentario y se reproducirá el tema, así que cuidado)",
    "th09 Music Room spoiler 1": "**** Nota ****",
    "th09 Music Room spoiler 2": "Este tema todavía no se ha reproducido en el juego.",
    "th09 Music Room spoiler 3": "Puedes escuchar una muestra, pero no se mostrará el título.",
    "th08 Spell Dissolve": "\"Conjuro disperso\"",
    "th08 Spell Resurrection": "\"Resurrección\"",
    "th08 Bomb Reimu": "Signo de espíritu \"Orbe de fantasía\"",
    "th08 Bomb Reimu Last": "Espíritu divino \"Sello de fantasía -Parpadeo-\"",
    "th08 Bomb Yukari": "Signo de límite \"Barrera cuádruple\"",
    "th08 Bomb Yukari Last": "Límite \"Barrera cuádruple de la noche imperecedera\"",
    "th08 Bomb Marisa Last": "Magicañón \"Chispa final\"",
    "th08 Bomb Alice": "Signo de magia \"Sacrificio taimado\"",
    "th08 Bomb Alice Last": "Magipulación \"Retorno a la inanimacidad\"",
    "th08 Bomb Sakuya Last": "Funeral ilusorio \"Asesino fantasmal en la niebla nocturna\"",
    "th08 Bomb Remilia": "Signo escarlata \"El rojo castillo sin noche\"",
    "th08 Bomb Remilia Last": "Demonio escarlata \"Demonio escarlata\"",
    "th08 Bomb Youmu": "Signo de humano \"Corte del mundo presente\"",
    "th08 Bomb Youmu Last": "Oni humano \"Corte del eterno futuro\"",
    "th08 Bomb Yuyuko": "Signo de muerte \"Sueño cadavérico\"",
    "th08 Bomb Yuyuko Last": "Mariposa de la muerte \"Sueño eterno en el país de los sueños\""
}