{
    "th06_01": "Un sueño más escarlata que rojo",
    "th06_02": "Un alma tan roja como un farolillo chino",
    "th06_03": "Apariciones acechando la noche",
    "th06_04": "Elfa de la medialuna",
    "th06_05": "Chica varonil enamorada",
    "th06_06": "Salón de té de Shanghai ~ Té chino",
    "th06_07": "Shanghai Alice del Meiji 17",
    "th06_08": "Voile, la biblioteca mágica",
    "th06_09": "Chica encerrada ~ La habitación secreta de la chica",
    "th06_10": "La sirvienta y el reloj de bolsillo de sangre",
    "th06_11": "Reloj lunar ~ Dial de luna",
    "th06_12": "La joven descendiente de Tepes",
    "th06_13": "Septeto para una princesa muerta",
    "th06_14": "Festival centenario para chicas mágicas",
    "th06_15": "¿U.N. Owen era ella?",
    "th06_16": "Una eternidad más efímera que escarlata",
    "th06_17": "Torre escarlata ~ Sueño oriental...",
    "th14_01": "Misteriosa vara de purificación",
    "th14_02": "Lago de Niebla",
    "th14_03": "Sirena de tierras inexploradas",
    "th14_04": "El ir y venir de humanos y youkai al canal",
    "th14_05": "Dullahan bajo los sauces",
    "th14_06": "Bosque de Bambú de la luna llena",
    "th14_07": "Solitaria mujer-lobo",
    "th14_08": "Tormenta mágica",
    "th14_09": "Joururi ilusorio",
    "th14_10": "El Castillo de la Aguja Brillante hundiéndose en el aire",
    "th14_11": "Ideología inversa",
    "th14_12": "El exagerado torreón del castillo",
    "th14_13": "Diminutos de la aguja brillante ~ Pequeña princesa",
    "th14_14": "Nubes de tormenta de poder mágico",
    "th14_15": "Ritmo primordial ~ Ritmo prístino",
    "th14_16": "El poder mágico del mazo",
    "th14_17": "Extraños y misteriosos instrumentos",
    "th125_01": "Cazanoticias",
    "th125_02": "El misterio de tu ciudad",
    "th125_03": "Moderna colonia youkai",
    "th125_04": "Fortaleza del némesis",
    "th125_05": "Campana de Avici ~ Pesadilla infinita",
    "th125_06": "La Montaña Youkai ~ Montaña misteriosa"
}