{
    "0": "Signo de luna \"Rayo de luz de luna\"",
    "1": "Signo de noche \"Pájaro nocturno\"",
    "2": "Signo de oscuridad \"Demarcación\"",
    "3": "Signo de hielo \"Caída de carámbano\"",
    "4": "Signo de granizo \"Tormenta de granizo\"",
    "5": "Signo de congelación \"Congelación perfecta\"",
    "6": "Signo de nieve \"Ventisca de diamantes\"",
    "7": "Signo de flor \"Sublime flor fragante\"",
    "8": "Signo de flor \"Selaginella 9\"",
    "9": "Signo de arcoíris \"Carillón de arcoíris colorido\"",
    "10": "Signo de ilusión \"Flor de kudzu de sueño ilusorio\"",
    "11": "Signo colorido \"Lluvia de colores vivos\"",
    "12": "Signo colorido \"Danza caótica de luces de colores\"",
    "13": "Signo colorido \"Tifón de colores intentos\"",
    "14": "Signo de fuego \"Brillo de Agni\"",
    "15": "Signo de agua \"Princesa ondina\"",
    "16": "Signo de madera \"Cuerno de sílfide\"",
    "17": "Signo de tierra \"Furia de trilito\"",
    "18": "Signo de metal \"Fatiga metálica\"",
    "19": "Signo de fuego \"Brillo de Agni de nivel alto\"",
    "20": "Signo de madera \"Cuerno de sílfide de nivel alto\"",
    "21": "Signo de tierra \"Furia de trilito de nivel alto\"",
    "22": "Signo de fuego \"Resplandor de Agni\"",
    "23": "Signo de agua \"Encierro bajo el lago\"",
    "24": "Signo de madera \"Tormenta verde\"",
    "25": "Signo de tierra \"Temblor de trilito\"",
    "26": "Signo de metal \"Dragón de plata\"",
    "27": "Signo de fuego y tierra \"Crómlech de lava\"",
    "28": "Signo de madera y fuego \"Incendio forestal\"",
    "29": "Signo de agua y madera \"Duende de agua\"",
    "30": "Signo de metal y agua \"Veneno de mercurio\"",
    "31": "Signo de tierra y metal \"Megalito esmeralda\"",
    "32": "Prestidigitación \"Desorientación\"",
    "33": "Prestidigitación \"Desorientación hechizante\"",
    "34": "Existencia ilusoria \"Cadáver de reloj\"",
    "35": "Imagen ilusoria \"Reloj de luna\"",
    "36": "Técnica secreta de sirvienta \"Marioneta\"",
    "37": "Fantasma ilusorio \"Jack la hierba de locura\"",
    "38": "Mundo de ilusión \"El mundo\"",
    "39": "Técnica secreta de sirvienta \"Muñeca asesina\"",
    "40": "Prestidigitación \"Sumisión eterna\"",
    "41": "Castigo celestial \"Estrella de David\"",
    "42": "Signo de inframundo \"Inframundo escarlata\"",
    "43": "Maldición \"Maldición de Vlad Tepes\"",
    "44": "Signo escarlata \"Disparo escarlata\"",
    "45": "\"Magia roja\"",
    "46": "Castigo divino \"Joven señora demoníaca\"",
    "47": "Signo de infierno \"Montaña de un millar de espinas\"",
    "48": "Técnica divina \"Ilusión vampírica\"",
    "49": "Signo escarlata \"Maestra escarlata\"",
    "50": "\"Gensokyo escarlata\"",
    "51": "Signo de luna \"Selene silenciosa\"",
    "52": "Signo de sol \"Fulgor espléndido\"",
    "53": "Signo de fuego, agua, madera, tierra y metal \"Piedra filosofal\"",
    "54": "Tabú \"Trampa de arándanos\"",
    "55": "Tabú \"Lævateinn\"",
    "56": "Tabú \"Cuatro en una\"",
    "57": "Tabú \"Kagome, Kagome\"",
    "58": "Tabú \"Laberinto de amor\"",
    "59": "Bombardeo prohibido \"Ruptura del arco estelar\"",
    "60": "Bombardeo prohibido \"Catadióptrico\"",
    "61": "Bombardeo prohibido \"Reloj que aleja el pasado\"",
    "62": "Bombardeo secreto \"¿Y no quedará ninguna?\"",
    "63": "QED \"Ondas de los 495 años\""
}