{
    "0": "Signo de escarcha \"Columnas de escarcha\"",
    "1": "Signo de escarcha \"Columnas de escarcha -Lunático-\"",
    "2": "Signo de frío \"Frío persistente -Fácil-\"",
    "3": "Signo de frío \"Frío persistente\"",
    "4": "Signo de frío \"Frío persistente -Difícil-\"",
    "5": "Signo de frío \"Frío persistente -Lunático-\"",
    "6": "Signo de invierno \"Flor marchita -Fácil-\"",
    "7": "Signo de invierno \"Flor marchita\"",
    "8": "Signo blanco \"Rayo ondulante\"",
    "9": "Signo místico \"Girar la mesa\"",
    "10": "Signo de ermitaño \"Huevo de fénix -Fácil-\"",
    "11": "Signo de ermitaño \"Huevo de fénix\"",
    "12": "Signo de ermitaño \"Fénix de alas desplegadas\"",
    "13": "Signo de ermitaño \"Fénix de alas desplegadas -Lunático-\"",
    "14": "Signo de shikigami \"Vuelo de Seimei -Fácil-\"",
    "15": "Signo de shikigami \"Vuelo de Seimei\"",
    "16": "Yin Yang \"Douman-Seimei\"",
    "17": "Yin Yang \"Gran insignia de Seimei\"",
    "18": "Signo de cielo \"Estruendo de sabio inmortal -Fácil-\"",
    "19": "Signo de cielo \"Estruendo de sabio inmortal\"",
    "20": "Signo de vuelo \"Vuelo de Idaten\"",
    "21": "Signo infantil \"Danza salvaje de Dharmapala\"",
    "22": "Signo de ermitaño \"Encarnación inmortal -Fácil-\"",
    "23": "Signo de ermitaño \"Encarnación inmortal\"",
    "24": "Signo de oni \"Konjin de la puerta del demonio\"",
    "25": "Signo de dirección \"Kimontonkou\"",
    "26": "Signo de tirititera \"Bunraku de doncella\"",
    "27": "Signo de tirititera \"Bunraku de doncella -Lunático-\"",
    "28": "Signo azul \"Benevolentes muñecas francesas -Fácil-\"",
    "29": "Signo azul \"Benevolentes muñecas francesas\"",
    "30": "Signo azul \"Benevolentes muñecas francesas -Difícil-\"",
    "31": "Signo azul \"Benevolentes muñecas de Orleans\"",
    "32": "Signo escarlata \"Pelirrojas muñecas holandesas -Fácil-\"",
    "33": "Signo escarlata \"Pelirrojas muñecas holandesas\"",
    "34": "Signo blanco \"Pálidas muñecas rusas\"",
    "35": "Signo blanco \"Pálidas muñecas rusas -Lunático-\"",
    "36": "Signo oscuro \"Neblinosas muñecas londinenses -Fácil-\"",
    "37": "Signo oscuro \"Neblinosas muñecas londinenses\"",
    "38": "Signo de ciclo \"Reencarnantes muñecas tibetanas\"",
    "39": "Signo de elegancia \"Primaverales muñecas de Kyoto\"",
    "40": "Maldición \"Espeluznantes muñecas de Shanghai -Fácil-\"",
    "41": "Maldición \"Espeluznantes muñecas de Shanghai\"",
    "42": "Maldición \"Espeluznantes muñecas de Shanghai -Difícil-\"",
    "43": "Maldición \"Ahorcadas muñecas de Hourai\"",
    "44": "Signo de ruido \"Estruendo fantasmal -Fácil-\"",
    "45": "Signo de ruido \"Estruendo fantasmal\"",
    "46": "Signo de ruido \"Poltergeist en vivo\"",
    "47": "Signo de ruido \"Poltergeist en vivo -Lunático-\"",
    "48": "Actuación de cuerda \"Guarneri del Gesù -Fácil-\"",
    "49": "Actuación de cuerda \"Guarneri del Gesù\"",
    "50": "Cuerdas divinas \"Stradivarius\"",
    "51": "Cuerdas falsas \"Pseudo Stradivarius\"",
    "52": "Trompeta fantasmal \"Espectro de Hino -Fácil-\"",
    "53": "Trompeta fantasmal \"Espectro de Hino\"",
    "54": "Trompeta sombría \"Fantasma de Clifford\"",
    "55": "Trompeta fantasmal \"Fantasma de Clifford -Lunático-\"",
    "56": "Teclado sombrío \"Actuación melancólica de Fazioli -Fácil-\"",
    "57": "Teclado sombrío \"Actuación melancólica de Fazioli\"",
    "58": "Teclado fantasmal \"Actuación espiritual de Bösendorfer\"",
    "59": "Teclado fantasmal \"Actuación espiritual de Bösendorfer -Lunático-\"",
    "60": "Concierto fúnebre \"Concerto distorsionador -Fácil-\"",
    "61": "Concierto fúnebre \"Concerto distorsionador\"",
    "62": "Ruido fúnebre \"Rivera del Estigia\"",
    "63": "Ruido fúnebre \"Rivera del Estigia -Lunático-\"",
    "64": "Gran concierto fúnebre \"Concerto grosso fúnebre -Fácil-\"",
    "65": "Gran concierto fúnebre \"Concerto grosso fúnebre\"",
    "66": "Gran concierto fúnebre \"Concerto grosso fúnebre revisado\"",
    "67": "Gran concierto fúnebre \"Concerto grosso fúnebre maravilloso\"",
    "68": "Espada fantasmal \"Ayuna de los preta jovenes -Fácil-\"",
    "69": "Espada fantasmal \"Ayuna de los preta jovenes\"",
    "70": "Espada de los preta \"Pergamino del reino de los preta\"",
    "71": "Espada del rey hambriento \"Castigo de los diez reyes a los preta\"",
    "72": "Espada del reino de los naraka \"200 yojana en un corte -Fácil-\"",
    "73": "Espada del reino de los naraka \"200 yojana en un corte\"",
    "74": "Espada del naraka ardiente \"Estilo del corte fugaz del viento kármico\"",
    "75": "Espada del dios naraka \"Corte divino fugaz del viento kármico\"",
    "76": "Espada del reino animal \"Castigo kármico de los holgazanes -Fácil-\"",
    "77": "Espada del reino animal \"Castigo kármico de los holgazanes\"",
    "78": "Espada de los asura \"Obsesión del mundo presente\"",
    "79": "Espada de los asura \"Obsesión del mundo presente -Lunático-\"",
    "80": "Espada del reino humano \"Delirios de iluminación -Fácil-\"",
    "81": "Espada del reino humano \"Delirios de iluminación\"",
    "82": "Espada de la era humana \"Desilusión inminente\"",
    "83": "Espada del dios humano \"Aceptación de la verdad eterna\"",
    "84": "Espada del reino de los deva \"Cinco signos del deva moribundo -Fácil-\"",
    "85": "Espada del reino de los deva \"Cinco signos del deva moribundo\"",
    "86": "Espada del reino celestial \"Desagrado de los siete haku\"",
    "87": "Espada del dios celestial \"Tres kon, siete haku\"",
    "88": "Espada de los seis reinos \"Propósito único y kalpa infinito -Fácil-\"",
    "89": "Espada de los seis reinos \"Propósito único y kalpa infinito\"",
    "90": "Espada de los seis reinos \"Propósito único y kalpa infinito -Difícil-\"",
    "91": "Espada de los seis reinos \"Propósito único y kalpa infinito -Lunático-\"",
    "92": "Pueblo desaparecido \"Pueblo de los perdidos -Alma errante-\"",
    "93": "Pueblo desaparecido \"Pueblo de los perdidos -Pecados pasados-\"",
    "94": "Pueblo desaparecido \"Pueblo de los perdidos -Camino sin sendero-\"",
    "95": "Pueblo desaparecido \"Pueblo de los perdidos -Suicidio-\"",
    "96": "Danza mortal \"Ley de la mortalidad -Desconcierto-\"",
    "97": "Danza mortal \"Ley de la mortalidad -Mariposa de la muerte-\"",
    "98": "Danza mortal \"Ley de la mortalidad -Polilla venenosa-\"",
    "99": "Danza mortal \"Ley de la mortalidad -Mundo de los demonios-\"",
    "100": "Alma floral \"Mariposa fantasmal\"",
    "101": "Alma floral \"Papilio\"",
    "102": "Alma floral \"Mariposa arraigada\"",
    "103": "Alma floral \"Delirio de mariposa\"",
    "104": "Melodía sutil \"Almacén de Hirokawa -Espíritu falso-\"",
    "105": "Melodía sutil \"Almacén de Hirokawa -Fantasma-\"",
    "106": "Melodía sutil \"Almacén de Hirokawa -Espíritu fantasmal-\"",
    "107": "Melodía sutil \"Almacén de Hirokawa -Espíritu divino-\"",
    "108": "Signo de cerezo \"Perfectas flores negras -Sello-\"",
    "109": "Signo de cerezo \"Perfectas flores negras -Perdición-\"",
    "110": "Signo de cerezo \"Perfectas flores negras -Sueño primaveral-\"",
    "111": "Signo de cerezo \"Perfectas flores negras -Floración-\"",
    "112": "\"Resurrección de la mariposa -Refloración del 10%%-\"",
    "113": "\"Resurrección de la mariposa -Refloración del 30%%-\"",
    "114": "\"Resurrección de la mariposa -Refloración del 50%%-\"",
    "115": "\"Resurrección de la mariposa -Refloración del 80%%-\"",
    "116": "Signo de oni \"Oni azul, oni rojo\"",
    "117": "Dios oni \"Bishamonten volador\"",
    "118": "Shikigami \"Pensamientos del zorro ermitaño\"",
    "119": "Shikigami \"Banquete de los doce generales divinos\"",
    "120": "Resplandor de shikigami \"Láser de kitsune y tanuki\"",
    "121": "Resplandor de shikigami \"Acoso encantador por todas partes\"",
    "122": "Resplandor de shikigami \"Princesa Tenko -Ilusión-\"",
    "123": "Disparo de shikigami \"Budista definitivo\"",
    "124": "Disparo de shikigami \"Contacto unilateral\"",
    "125": "Shikigami \"Chen\"",
    "126": "\"Contrato de Kokkuri-san\"",
    "127": "Dios ilusión \"Linaje de Izuna Gongen\"",
    "128": "Shikigami \"Protección de Zenki y Goki\"",
    "129": "Shikigami \"Posesión de Dakini-ten\"",
    "130": "Barrera \"Maldición de los sueños y la realidad\"",
    "131": "Barrera \"Equilibrio entre el movimiento y el reposo\"",
    "132": "Barrera \"Mezcla de la luz y la oscuridad\"",
    "133": "Espíritu maligno \"Xanadú de lo recto y lo curvo\"",
    "134": "Espíritu maligno \"Rapto de Yukari Yakumo\"",
    "135": "Espíritu maligno \"Mariposa cautivadora viviendo en el templo Zen\"",
    "136": "Espíritu siniestro \"Doble mariposa negra de la muerte\"",
    "137": "Shikigami \"Ran Yakumo\"",
    "138": "\"Límite entre humanos y youkai\"",
    "139": "Barrera \"Límite entre la vida y la muerte\"",
    "140": "Arcano de Yukari \"Barrera danmaku\""
}