{
    "0": "Signo de luciérnaga \"Meteorito sobre la tierra\"",
    "1": "Signo de luciérnaga \"Cometa sobre la tierra\"",
    "2": "Signo de farol \"Fenómeno de luciérnaga\"",
    "3": "Signo de farol \"Fenómeno de luciérnaga\"",
    "4": "Signo de farol \"Fenómeno de luciérnaga\"",
    "5": "Signo de farol \"Fenómeno de luciérnaga\"",
    "6": "Signo de arrastre \"Pequeños insectos\"",
    "7": "Signo de arrastre \"Tormenta de pequeños insectos\"",
    "8": "Signo de arrastre \"Tormenta de insectos nocturnos\"",
    "9": "Signo de arrastre \"Tornado de insectos nocturnos\"",
    "10": "Insecto nocturno \"Reclusión de la noche eterna\"",
    "11": "Insecto nocturno \"Reclusión de la noche eterna\"",
    "12": "Insecto nocturno \"Reclusión de la noche eterna\"",
    "13": "Signo vocal \"Ulular en la noche\"",
    "14": "Signo vocal \"Ulular en la noche\"",
    "15": "Signo vocal \"Ulular del búho cornudo\"",
    "16": "Signo vocal \"Ulular del búho cornudo\"",
    "17": "Signo de polilla \"Aleteo de la esfinge\"",
    "18": "Signo de polilla \"Aleteo de la esfinge\"",
    "19": "Signo de toxina \"Escamas de la polilla venenosa\"",
    "20": "Toxina letal \"Danza en la oscuridad de la polilla venenosa\"",
    "21": "Signo de halcón \"Descenso desdichado\"",
    "22": "Signo de halcón \"Descenso desdichado\"",
    "23": "Signo de halcón \"Descenso desdichado\"",
    "24": "Signo de halcón \"Descenso desdichado\"",
    "25": "Ceguera nocturna \"Canción del gorrión nocturno\"",
    "26": "Ceguera nocturna \"Canción del gorrión nocturno\"",
    "27": "Ceguera nocturna \"Canción del gorrión nocturno\"",
    "28": "Ceguera nocturna \"Canción del gorrión nocturno\"",
    "29": "Gorrión nocturno \"Maestra del coro de medianoche\"",
    "30": "Gorrión nocturno \"Maestra del coro de medianoche\"",
    "31": "Gorrión nocturno \"Maestra del coro de medianoche\"",
    "32": "Nacimiento espiritual \"Primera pirámide\"",
    "33": "Nacimiento espiritual \"Primera pirámide\"",
    "34": "Nacimiento espiritual \"Primera pirámide\"",
    "35": "Nacimiento espiritual \"Primera pirámide\"",
    "36": "Signo de origen \"Efimeralidad 137\"",
    "37": "Signo de origen \"Efimeralidad 137\"",
    "38": "Signo de origen \"Efimeralidad 137\"",
    "39": "Signo de ambición \"Crisis de Buretsu\"",
    "40": "Signo de ambición \"Crisis de Masakado\"",
    "41": "Signo de ambición \"Crisis de Yoshimitsu\"",
    "42": "Signo de ambición \"Crisis del Cuartel General\"",
    "43": "Signo de la tierra \"Tres Tesoros Sagrados - Espada\"",
    "44": "Signo de la tierra \"Tres Tesoros Sagrados - Joya\"",
    "45": "Signo de la tierra \"Tres Tesoros Sagrados - Espejo\"",
    "46": "Política nacional \"Tres Tesoros Sagrados - País\"",
    "47": "Signo de final \"Emperador fantasmal\"",
    "48": "Signo de final \"Emperador fantasmal\"",
    "49": "Pseudohistoria \"La leyenda de Gensokyo\"",
    "50": "Pseudohistoria \"La leyenda de Gensokyo\"",
    "51": "Futuro \"Takamagahara\"",
    "52": "Futuro \"Takamagahara\"",
    "53": "Futuro \"Takamagahara\"",
    "54": "Signo de sueño \"Barrera dúplex\"",
    "55": "Signo de sueño \"Barrera dúplex\"",
    "56": "Tierra de sueños \"Gran barrera dúplex\"",
    "57": "Tierra de sueños \"Gran barrera dúplex\"",
    "58": "Signo de espíritu \"Sello de fantasía -Dispersión-\"",
    "59": "Signo de espíritu \"Sello de fantasía -Dispersión-\"",
    "60": "Espíritu diseminado \"Sello de fantasía -Soledad-\"",
    "61": "Espíritu diseminado \"Sello de fantasía -Soledad-\"",
    "62": "Signo de sueño \"Círculo sellador del mal\"",
    "63": "Signo de sueño \"Círculo sellador del mal\"",
    "64": "Técnica divina \"Círculo omnidireccional atademonios\"",
    "65": "Técnica divina \"Círculo omnidireccional matadragones\"",
    "66": "Signo de espíritu \"Sello de fantasía -Concentración-\"",
    "67": "Signo de espíritu \"Sello de fantasía -Concentración-\"",
    "68": "Espíritu migratorio \"Sello de fantasía -Desconsuelo-\"",
    "69": "Espíritu migratorio \"Sello de fantasía -Desconsuelo-\"",
    "70": "Límite \"Barrera danmaku dúplex\"",
    "71": "Límite \"Barrera danmaku dúplex\"",
    "72": "Gran barrera \"Barrera danmaku Hakurei\"",
    "73": "Gran barrera \"Barrera danmaku Hakurei\"",
    "74": "Espíritu divino \"Sello de fantasía -Parpadeo-\"",
    "75": "Espíritu divino \"Sello de fantasía -Parpadeo-\"",
    "76": "Espíritu divino \"Sello de fantasía -Parpadeo-\"",
    "77": "Signo de magia \"Vía Láctea\"",
    "78": "Signo de magia \"Vía Láctea\"",
    "79": "Espacio mágico \"Cinturón de asteroides\"",
    "80": "Espacio mágico \"Cinturón de asteroides\"",
    "81": "Signo de magia \"Ensueño de polvo estelar\"",
    "82": "Signo de magia \"Ensueño de polvo estelar\"",
    "83": "Magia negra \"Horizonte de sucesos\"",
    "84": "Magia negra \"Horizonte de sucesos\"",
    "85": "Signo de amor \"Láser no direccional\"",
    "86": "Signo de amor \"Láser no direccional\"",
    "87": "Tormenta de amor \"Tifón de luz de las estrellas\"",
    "88": "Tormenta de amor \"Tifón de luz de las estrellas\"",
    "89": "Signo de amor \"Chispa maestra\"",
    "90": "Signo de amor \"Chispa maestra\"",
    "91": "Corazón amoroso \"Chispa doble\"",
    "92": "Corazón amoroso \"Chispa doble\"",
    "93": "Signo de luz \"Rayo de luz terrestre\"",
    "94": "Signo de luz \"Rayo de luz terrestre\"",
    "95": "Estallido de luz \"Disparar a la luna\"",
    "96": "Estallido de luz \"Disparar a la luna\"",
    "97": "Magicañón \"Chispa final\"",
    "98": "Magicañón \"Chispa final\"",
    "99": "Magicañón \"Chispa maestra final\"",
    "100": "Signo de onda \"Hipnosis de ojos rojos (Tiemblamentes)\"",
    "101": "Signo de onda \"Hipnosis de ojos rojos (Tiemblamentes)\"",
    "102": "Onda de ilusión \"Hipnosis de ojos rojos (Rompementes)\"",
    "103": "Onda de ilusión \"Hipnosis de ojos rojos (Rompementes)\"",
    "104": "Signo lunático \"Afinación alucionatoria (Afinación visionaria)\"",
    "105": "Signo lunático \"Afinación alucionatoria (Afinación visionaria)\"",
    "106": "Mirada lunática \"Afinación lunática fija (Buscailusiones)\"",
    "107": "Mirada lunática \"Afinación lunática fija (Buscailusiones)\"",
    "108": "Signo estático \"Detener la vida y el espíritu (Onda estática)\"",
    "109": "Signo estático \"Detener la vida y el espíritu (Onda estática)\"",
    "110": "Indolencia \"Detener la vida y el espíritu (Detienementes)\"",
    "111": "Indolencia \"Detener la vida y el espíritu (Detienementes)\"",
    "112": "Signo de difusión \"Luna de la verdad (Luna llena invisible)\"",
    "113": "Signo de difusión \"Luna de la verdad (Luna llena invisible)\"",
    "114": "Signo de difusión \"Luna de la verdad (Luna llena invisible)\"",
    "115": "Signo de difusión \"Luna de la verdad (Luna llena invisible)\"",
    "116": "Ojos lunares \"Hipnosis del conejo lunar (Telemesmerismo)\"",
    "117": "Ojos lunares \"Hipnosis del conejo lunar (Telemesmerismo)\"",
    "118": "Ojos lunares \"Hipnosis del conejo lunar (Telemesmerismo)\"",
    "119": "Núcleo espacial \"La Tierra en un jarrón\"",
    "120": "Núcleo espacial \"La Tierra en un jarrón\"",
    "121": "Núcleo espacial \"La Tierra en un jarrón\"",
    "122": "Núcleo espacial \"La Tierra en un jarrón\"",
    "123": "Diosa despertada \"Recuerdos de la Era de los Dioses\"",
    "124": "Diosa despertada \"Recuerdos de la Era de los Dioses\"",
    "125": "Signo de diosa \"Genealogía de los seres celestiales\"",
    "126": "Signo de diosa \"Genealogía de los seres celestiales\"",
    "127": "Renacimiento \"El juego de la vida\"",
    "128": "Renacimiento \"El juego de la vida\"",
    "129": "Resurrección \"El juego del crecimiento\"",
    "130": "Resurrección \"El juego del crecimiento\"",
    "131": "Diosa manipuladora \"Estratagema de Omoikane\"",
    "132": "Diosa manipuladora \"Estratagema de Omoikane\"",
    "133": "Mente de diosa \"Cerebro de Omoikane\"",
    "134": "Mente de diosa \"Cerebro de Omoikane\"",
    "135": "Maldición de los cielos \"Apolo 13\"",
    "136": "Maldición de los cielos \"Apolo 13\"",
    "137": "Maldición de los cielos \"Apolo 13\"",
    "138": "Maldición de los cielos \"Apolo 13\"",
    "139": "Esotérica \"Enterramiento astronómico\"",
    "140": "Esotérica \"Enterramiento astronómico\"",
    "141": "Esotérica \"Enterramiento astronómico\"",
    "142": "Esotérica \"Enterramiento astronómico\"",
    "143": "Arcano prohibido \"Elixir de Hourai\"",
    "144": "Arcano prohibido \"Elixir de Hourai\"",
    "145": "Arcano prohibido \"Elixir de Hourai\"",
    "146": "Arcano prohibido \"Elixir de Hourai\"",
    "147": "Signo de medicina \"La galaxia en un jarrón\"",
    "148": "Signo de medicina \"La galaxia en un jarrón\"",
    "149": "Signo de medicina \"La galaxia en un jarrón\"",
    "150": "Signo de medicina \"La galaxia en un jarrón\"",
    "151": "Tarea imposible \"Joya del dragón -Disparos de cinco colores-\"",
    "152": "Tarea imposible \"Joya del dragón -Disparos de cinco colores-\"",
    "153": "Tesoro divino \"Proyectil brillante del dragón\"",
    "154": "Tesoro divino \"Proyectil brillante del dragón\"",
    "155": "Tarea imposible \"Cuenco de piedra de Buda -Voluntad indómita-\"",
    "156": "Tarea imposible \"Cuenco de piedra de Buda -Voluntad indómita-\"",
    "157": "Tesoro divino \"Diamante budista\"",
    "158": "Tesoro divino \"Diamante budista\"",
    "159": "Tarea imposible \"Túnica de la rata de fuego -Mente paciente-\"",
    "160": "Tarea imposible \"Túnica de la rata de fuego -Mente paciente-\"",
    "161": "Tesoro divino \"Escudo de salamandra\"",
    "162": "Tesoro divino \"Escudo de salamandra\"",
    "163": "Tarea imposible \"Concha de cauri de golondrina -Vida eterna-\"",
    "164": "Tarea imposible \"Concha de cauri de golondrina -Vida eterna-\"",
    "165": "Tesoro divino \"Fuente infinita de la vida\"",
    "166": "Tesoro divino \"Fuente infinita de la vida\"",
    "167": "Tarea imposible \"Rama de orbes de Hourai -Danmaku arcoíris-\"",
    "168": "Tarea imposible \"Rama de orbes de Hourai -Danmaku arcoíris-\"",
    "169": "Tesoro divino \"Rama enjoyada de Hourai -Paraíso onírico-\"",
    "170": "Tesoro divino \"Rama enjoyada de Hourai -Paraíso onírico-\"",
    "171": "\"Fin de la noche imperecedera -Luna nueva-\"",
    "172": "\"Fin de la noche imperecedera -Luna creciente-\"",
    "173": "\"Fin de la noche imperecedera -Primer cuarto de luna-\"",
    "174": "\"Fin de la noche imperecedera -Matsuyoi-\"",
    "175": "\"Fin de la noche imperecedera -Once de la noche-\"",
    "176": "\"Fin de la noche imperecedera -Media para la medianoche-\"",
    "177": "\"Fin de la noche imperecedera -Medianoche-\"",
    "178": "\"Fin de la noche imperecedera -Media pasada la medianoche-\"",
    "179": "\"Fin de la noche imperecedera -Una de la madrugada-\"",
    "180": "\"Fin de la noche imperecedera -Media pasada la una-\"",
    "181": "\"Fin de la noche imperecedera -Noche profunda-\"",
    "182": "\"Fin de la noche imperecedera -Media pasada las dos-\"",
    "183": "\"Fin de la noche imperecedera -Tres de la madrugada-\"",
    "184": "\"Fin de la noche imperecedera -Media pasada las tres-\"",
    "185": "\"Fin de la noche imperecedera -Cuatro de la madrugada-\"",
    "186": "\"Fin de la noche imperecedera -Media pasada las cuatro-\"",
    "187": "\"Fin de la noche imperecedera -Niebla matinal-\"",
    "188": "\"Fin de la noche imperecedera -Amanecer-\"",
    "189": "\"Fin de la noche imperecedera -Lucero del alba-\"",
    "190": "\"Fin de la noche imperecedera -Despertar del mundo-\"",
    "191": "Pasado \"Historia ancestral -Antigua historia-\"",
    "192": "Reencarnación \"Puente Ichijo del regreso\"",
    "193": "Futuro \"Nueva historia fantasmal -Siguiente historia-\"",
    "194": "Edicto restrictivo \"Maldición de Tsuki-no-Iwakasa\"",
    "195": "Inmortal \"Pájaro de fuego -Alas ardientes del fénix-\"",
    "196": "Fujiwara \"Imperfección del santuario indulgente\"",
    "197": "Inmortal \"Dimensión de Xu Fu\"",
    "198": "Clemencia \"La muerte de un hombre honesto\"",
    "199": "Ser vacío \"Wu\"",
    "200": "Eterno \"Cola de fénix\"",
    "201": "Hourai \"Viento del sur, cielo despejado -Volcán de Fujiyama-\"",
    "202": "\"Posesión del fénix\"",
    "203": "\"Muñeca de Hourai\"",
    "204": "\"Tiroteo imperecedero\"",
    "205": "\"Tormenta intempestiva de mariposas\"",
    "206": "\"Pájaro nocturno ciego\"",
    "207": "\"Emperador de Oriente\"",
    "208": "\"Mirada de la luna fantasmal difusa (Ojos rojos lunáticos)\"",
    "209": "\"Tela atrapamariposas de la araña celestial\"",
    "210": "\"Mar de árboles de Hourai\"",
    "211": "\"Renacimiento del fénix\"",
    "212": "\"Embaucadora ancestral\"",
    "213": "\"Purificación absoluta\"",
    "214": "\"Naturaleza de la fantasía\"",
    "215": "\"Estrella centelleante\"",
    "216": "\"Desinflación del mundo\"",
    "217": "\"Corte del satélite reflectante en Matsuyoi\"",
    "218": "\"El espectro del gran guiñol\"",
    "219": "\"Destino escarlata\"",
    "220": "\"Nirvana inmaculado de Saigyouji\"",
    "221": "\"Barrera danmaku abundante -Ilusiones, espumas y sombras-\""
}