{
    "2": "Signo de otoño \"Ráfaga caduca\"",
    "3": "Signo de fruta \"Cosecha de colores cálidos\"",
    "4": "Senda marchita \"Hilera perdida\"",
    "5": "Batata asada \"Almacén de batatas\"",
    "12": "Celos \"Bombardero de celos\"",
    "13": "Campo maldito \"Sedimentos del río purificador\"",
    "14": "Técnica de resentimiento \"Retorno del rencor\"",
    "15": "Calamidad \"Muñecas Hina malditas\"",
    "21": "Signo de paraguas \"Bateo de una sola pierna\"",
    "22": "Cubo de pozo \"Volar en un pozo\"",
    "23": "Hilo pequeño \"Cuerda de Kandata\"",
    "24": "Signo de arcoíris \"Por encima del arcoíris\"",
    "25": "Cubo de pozo \"Destructor del pozo\"",
    "26": "Signo de veneno \"Araña japonesa del follage\"",
    "27": "Signo de paraguas \"Viajero bajo la nieve\"",
    "32": "Signo de agua \"Alfombra acuática\"",
    "33": "Signo de can \"Mordisco de rabia\"",
    "34": "Signo de río \"Línea divisoria\"",
    "35": "Nómada de las montañas \"Expulsor de Canaán\"",
    "36": "Kappa \"Shirikodama seco\"",
    "42": "Puño \"Caída del martillo celestial\"",
    "43": "Signo de ancla \"Gran amarre del barco fantasma\"",
    "44": "Relámpago \"Nyuudou electrificado\"",
    "45": "Inundación \"Venus de la sentina\"",
    "46": "Puño de hierro \"Nyuudou Nyoki\"",
    "47": "\"Plomada profunda\"",
    "52": "Oni de luz \"Hélice adamantina\"",
    "53": "Signo de oni \"Gran mota en el infierno de espinas\"",
    "54": "Signo de oni \"Espantosas ondas embravecidas\"",
    "55": "Infierno \"Suspiro del Purgatorio\"",
    "56": "Voz de oni \"Rugido aniquilador\"",
    "57": "Signo de oni \"Poder perdido\"",
    "62": "Signo de tigre \"Tigre hambriento\"",
    "63": "Signo de vara \"Vara de Nazrin\"",
    "64": "Signo de cielo \"Mandala de la tierra ardiente\"",
    "65": "Tesoro \"Fiebre del oro\"",
    "66": "Signo de tesoro \"Oro cegador\"",
    "71": "Fusión \"Blanco fundido\"",
    "72": "Signo de muerte \"Pueblo fantasma\"",
    "73": "Estrella gigante \"Gigante roja\"",
    "74": "\"Centro comercial de cadáveres\"",
    "75": "Signo de estrella \"Muerte de las grandes estrellas\"",
    "76": "Paseo del borracho \"Paseo aleatorio del gato\"",
    "77": "Siete estrellas \"Septentrión\"",
    "81": "Signo de corazón \"Amor abnegado\"",
    "82": "Signo de cerebro \"Huella del cerebro\"",
    "83": "Memoria \"Imperfección del ADN\"",
    "84": "Flor del corazón \"Rosa cohibida\"",
    "85": "\"Sueño de embrión\"",
    "86": "Recuerdo \"Vagos recuerdos de Kinkaku-ji\"",
    "87": "\"Rosa infernal\"",
    "90": "Temperamento \"Espada fogosa\"",
    "91": "Signo de trueno \"Pez relámpago\"",
    "92": "Terremoto \"Evacuación por el sendero empinado\"",
    "93": "Signo de joya \"Perla del dragón de cinco garras\"",
    "94": "Piedra angular \"Chimenea central\"",
    "95": "Palacio del Dragón \"Danza de los besugos y las solla\"",
    "96": "\"Cielo de percepción escarlata de toda la humanidad\"",
    "97": "Pez dragón \"Disparo nadador de la mensajera del Palacio del Dragón\"",
    "101": "Cerezo divino \"Ventisca de cerezos en flor\"",
    "102": "Signo de serpiente \"Serpiente de tierra\"",
    "103": "Río Hime \"Princesa verde jade\"",
    "104": "Pilar divino \"Onbashira meteórico\"",
    "105": "Anillo de hierro \"Anillo mítico\"",
    "106": "Senda fugaz \"Cruce de omiwatari\"",
    "107": "Dios nativo \"Mishaguji-sama\"",
    "111": "Desconocido \"Espejo púrpura\"",
    "112": "\"Yugyou Hijiri\"",
    "113": "Desconocido \"Manto rojo, manto azul\"",
    "114": "Sincretismo \"Manifestación de Mahavairocana\"",
    "115": "Desconocido \"Hanako-san en el baño\"",
    "116": "\"Espada estelar de los apologistas\"",
    "117": "\"Danmaku de otro mundo\"",
    "120": "Talismán \"Exorcismo de vendedores de subscripción de periódicos\"",
    "121": "Signo de estrella \"Nube de Oort\"",
    "122": "Milagro \"Viento divino de la era Kouan\"",
    "123": "Barrera \"Barrera repelente de paparazzi\"",
    "124": "Rueda astronómica \"Planetario solar\"",
    "125": "Signo de rana \"Sapo astuto\"",
    "126": "Signo de sueño \"Grieta dimensional de ensueño\"",
    "127": "Cometa \"Estrella centelleante\"",
    "128": "Exterminación de youkai \"Saqueadora de fuerza youkai\"",
    "131": "Reportaje \"Reportaje de entrenamiento de Hatate Himekaidou\"",
    "132": "Disparo continuo \"Disparo rápido\"",
    "133": "Sagacidad \"Ideografía tengu\"",
    "135": "Reportaje \"Reportaje coactivo de Aya Shameimaru\"",
    "136": "Telescopio \"Disparo simple\"",
    "137": "Instantánea \"Disparo veloz\"",
    "138": "\"Dominación ilusoria\""
}