{
    "0": "Signo de hielo \"Ventisca definitiva\"",
    "2": "Signo de agua \"Aletazo caudal\"",
    "6": "Signo de escama \"Ola escamosa\"",
    "8": "Signo de escama \"Ola violenta de escama invertida\"",
    "9": "Signo de escama \"Gran ola violenta de escama invertida\"",
    "10": "Signo de vuelo \"Cabeza voladora\"",
    "14": "Signo de cuello \"Disparo fijado\"",
    "16": "Signo de cuello \"Vuelo de rokurokubi\"",
    "18": "Cabeza voladora \"Cabeza multiplicativa\"",
    "20": "Cabeza voladora \"Séptima cabeza\"",
    "21": "Cabeza voladora \"Novena cabeza\"",
    "22": "Cabeza voladora \"Noche de dullahan\"",
    "26": "Signo de colmillo \"Diente canino bajo la luna\"",
    "28": "Transformación \"Colmillo triangular\"",
    "30": "Transformación \"Colmillo estelar\"",
    "32": "Rugido \"Rugido extraño\"",
    "34": "Rugido \"Aullido de luna llena\"",
    "36": "Signo de lobo \"Salto de anillo de estrellas\"",
    "38": "Lobo celestial \"Salto de alta velocidad\"",
    "40": "Heikyoku \"Repique de la campana de Jetavana\"",
    "44": "Espíritu vengativo \"Hoichi el Desorejado\"",
    "46": "Espíritu vengativo \"Gran espíritu vengativo de Taira\"",
    "48": "Signo de música \"Retorcida actuación musical\"",
    "50": "Signo de música \"Maliciosa actuación musical\"",
    "51": "Signo de música \"Doble partitura\"",
    "52": "Signo de koto \"Notas del koto de anitya\"",
    "56": "Signo de eco \"Reverberación de Heian\"",
    "58": "Signo de eco \"Sala insonorizada\"",
    "60": "Música de koto \"Marcha fúnebe de la revuelta social\"",
    "62": "Música de koto \"Réquiem de la revuelta social\"",
    "64": "Signo de engaño \"Ataque de la aguja inversa\"",
    "68": "Signo de inversión \"Danmaku a través del espejo\"",
    "70": "Signo de inversión \"El mal del espejo\"",
    "72": "Signo de inversión \"Este lado hacia abajo\"",
    "74": "Signo de inversión \"Volcar todo bajo el cielo\"",
    "76": "Arco invertido \"Arco del cielo y la tierra\"",
    "78": "Arco invertido \"Decreto del arco del cielo y la tierra\"",
    "80": "Giro radical \"Jerarquía invertida\"",
    "82": "Giro radical \"Desafío del cambio de aire\"",
    "84": "Proyectil pequeño \"Camino de los diminutos\"",
    "86": "Proyectil pequeño \"Camino de espinas de los diminutos\"",
    "88": "Mazo \"¡Crece!\"",
    "90": "Mazo \"¡Crece aún más!\"",
    "92": "Espada embrujada \"Espada de la aguja brillante\"",
    "96": "Mazo \"¡Tú creces!\"",
    "100": "\"Ataque a los diminutos\"",
    "102": "\"Muralla de Issun\"",
    "104": "\"Los siete Pulgarcitos\"",
    "106": "\"Los siete Issun-Boushi\"",
    "108": "Música de cuerda \"Conjunto tempestuoso\"",
    "109": "Música de cuerda \"Mundo de joururi\"",
    "110": "Primer tambor \"Intenso taiko de templo\"",
    "111": "Segundo tambor \"Espíritu vengativo de Aya-no-Tsuzumi\"",
    "112": "Tercer tambor \"Tres golpes a medianoche\"",
    "113": "Tambor de muerte \"Percusión del país\"",
    "114": "Quinto tambor \"Den-den daiko\"",
    "115": "Sexto tambor \"Golpeo alternativo\"",
    "116": "Séptimo tambor \"Cohete taiko de alta velocidad\"",
    "117": "Octavo tambor \"Furia del dios del trueno\"",
    "118": "\"Espectáculo de la dama azul\"",
    "119": "\"Ritmo prístino\""
}