{
    "2": "Signo de luciérnaga \"Estrella fija sobre la tierra\"",
    "3": "Signo de oscuridad \"El lado oscuro de la Luna\"",
    "4": "Signo de mariposa \"Tormenta de mariposas\"",
    "5": "Signo de noche \"Pájaro de la medianoche\"",
    "12": "Signo de nieve \"Ventisca de diamantes\"",
    "13": "Signo de frío \"Ola de frío\"",
    "14": "Signo de congelación \"Kelvin negativo\"",
    "15": "Signo de invierno \"Campeón del norte\"",
    "21": "Signo de luz \"Amaterasu\"",
    "22": "Signo de tirititera \"Muñecas en el mar\"",
    "23": "Signo de mortaja \"Lluvia en Showa\"",
    "24": "Signo de maldición \"Muñeca de paja kamikaze\"",
    "25": "Signo de malva real \"Mito no Mitsukuni\"",
    "26": "Signo rojo \"Muñeca de Mira Ceti\"",
    "27": "Signo de Japón \"Reino de Yamato\"",
    "31": "Signo de niebla \"Jardín gaseante\"",
    "32": "Conejo desbocado \"Fuga aturrullante\"",
    "33": "Signo de difusión \"Rama en flor de luna borrosa (Cohete en niebla)\"",
    "34": "Signo de veneno \"Aliento venenoso\"",
    "35": "Signo de onda \"Luna de ilusión (Medialuna invisible)\"",
    "36": "Confusión \"Caer en el delirio\"",
    "37": "Signo de deuda \"Medicamentos de Oonamuchi-sama\"",
    "38": "Sueño demente \"Sueño de locura (Mundo de los sueños)\"",
    "41": "Signo de sol y agua \"Protuberancia hidrogenada\"",
    "42": "Signo de flor \"Palma de la flor de loto de luces coloridas\"",
    "43": "Signo de agua y fuego \"Lluvia flogística\"",
    "44": "Voltereta colorida \"Pétalos revoloteando y hojas cayendo\"",
    "45": "Signo de luna y madera \"Satélite Himawari\"",
    "46": "Flor colorida \"Taijiquan de arcoíris\"",
    "47": "Signo de sol y luna \"Anillo de diamante real\"",
    "51": "Espada del conocimiento humano \"Corte del ángel giratorio\"",
    "52": "Signo de estrella \"Salto de escamas superpuestas\"",
    "53": "Espada de la obsesión \"Sangre de asura\"",
    "54": "Dios oni \"Jikoku-ten estruendoso\"",
    "55": "Espada de la estrella celestial \"Como el silencioso nirvana\"",
    "56": "Bakeneko \"Chen\"",
    "57": "Espada de los cuatro nacimientos \"Eco de los seres sin naturaleza\"",
    "61": "Signo de demonio \"El mundo en pesadilla\"",
    "62": "Signo de tiempo \"Efecto túnel\"",
    "63": "Signo escarlata \"Cuadrado mágico sangriento\"",
    "64": "Vacío \"Casilla de inflación\"",
    "65": "Murciélago escarlata \"Noche vampírica\"",
    "66": "Signo de plata \"Sirvienta perfecta\"",
    "67": "Diosa demonio \"Remilia Stoker\"",
    "71": "Elegancia fantasmal \"Trampa de luz del fallecimiento\"",
    "72": "Signo secreto \"Arcano de O-Daishi-sama\"",
    "73": "Signo de mariposa \"Lanza mortal del mon del papilio\"",
    "74": "Signo de austeridad \"Infinidad de tablas sagradas\"",
    "75": "Signo de muerte \"Vida de borracho, sueño de muerte\"",
    "76": "Superhombre \"En no Ozuno volador\"",
    "77": "\"Mariposa de muerte, luna flotante\"",
    "81": "Nueva tarea imposible \"Ilmenita lunar\"",
    "82": "Signo de medicina \"Píldora del sueño de la mariposa -Tipo pesadilla-\"",
    "83": "Nueva tarea imposible \"Piedra roja de Aja\"",
    "84": "Elixir \"Mar de mercurio\"",
    "85": "Nueva tarea imposible \"Techo continuo de Kinkaku-ji\"",
    "86": "Elixir secreto \"Incienso lunar\"",
    "87": "Nueva tarea imposible \"Misterita\"",
    "91": "Mentira \"Lengua de lobo\"",
    "92": "Canción de muerte \"Barca de la niebla profunda\"",
    "93": "Juicio \"Juicio de los diez reyes\"",
    "94": "Lluvia antigua \"Lluvia en el viaje liminal por el Yomi\"",
    "95": "Juicio \"Culpable o no culpable\"",
    "96": "Precio de muerte \"Valor de la vida\"",
    "97": "Juicio \"Juicio del cristal impoluto -Aya Shameimaru-\"",
    "100": "Tabú \"Fruta prohibida\"",
    "101": "Tabú \"Juegos prohibidos\"",
    "102": "Signo de límite \"Límite entre la forma y el vacío\"",
    "103": "Signo de límite \"Límite entre ondas y partículas\"",
    "104": "Personaje glorificado \"Aviso de Saint Germain\"",
    "105": "Hourai \"Mizue no Uranoshimako y las tortugas de los cinco colores\"",
    "106": "Qi de oni \"Laberinto de niebla profunda\"",
    "107": "\"Procesión nocturna del millón de demonios\""
}